limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    limit_req zone=general burst=20 nodelay;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
