# redirect all plain HTTP to HTTPS
server {
    listen 80;
    server_name flightcompanion.miguelrodrigues.dev;
    return 301 https://$host$request_uri;
}

limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;

server {
    listen 443 ssl;
    server_name flightcompanion.miguelrodrigues.dev;

    ssl_certificate /etc/letsencrypt/live/flightcompanion.miguelrodrigues.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/flightcompanion.miguelrodrigues.dev/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    limit_req zone=general burst=20 nodelay;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
